### PR TITLE
Add initial GitHub Actions build for Maven

### PR DESCRIPTION
**Pull request by chabala**
Runs your new Maven build, on every PR, and every push to main.
JaCoCo report included, and working.

### CODE REVIEW

**Comment by matty-r** [comment]
Cool, thanks for that. I'll take a look soon to get my head around it. I've not setup github actions before.

**Comment by chabala** [comment]
You can check out my draft PR in my fork where I was testing it out: https://github.com/chabala/urChat/pull/1

**Comment by matty-r** [comment]
Are you able to add `Main-Class: urChatBasic.frontend.DriverGUI` to the MANIFEST.MF that is in the .jar that is produced by this? At the moment it's not possible to run the .jar file as it throws an error "no main manifest attribute, in urchat-0.4.0.jar".

**Comment by chabala** [comment]
I can, though that's not really in scope for this PR. This is more about getting basic CI set up, rather than fine tuning your Maven build.

**Comment by matty-r** [comment]
> I can, though that's not really in scope for this PR. This is more about getting basic CI set up, rather than fine tuning your Maven build.

Understood, but i'd rather have it at least usable in it's basic state than not. Appreciate it!

**Review by matty-r — APPROVED** [review]

**Pull request merged**
